# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMBindings' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for MVVMBindings

  target 'MVVMBindingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMBindingsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
